### ISSUE TITLE
You can't uncover multiple includes with the same set of patterns as each other

### ISSUE THREAD

**Issue by Mihara** [colons/instant-coverage#16] opened 2017-02-06 11:44 UTC
At least, this is what I think happens. I have an include which includes another include and the tuple is reported as `('^first-include/', '^second-include/')` Adding this into uncovered_includes does not result in excluding the URLs from test.

**Comment by colons** [comment] 2017-02-08 09:07
Oh, weird; the reported includes should totally do that for you. Could you show me your urlconfs, or, better yet, a project I can reproduce this on?

**Comment by Mihara** [comment] 2017-02-08 09:46
It would be a bit difficult -- I can't show you my full project because work, and I don't really have the time to produce a minimal project replicating the problem from scratch right now. (We're using instant-coverage live -- I wanted to have at least *some* tests...)

I can give you some more detail though:

project/urls.py:
```
urlpatterns = patterns(
    '',
    ....
    url(r'^edu-data/', include('edu_data.urls')),
```

edu_data/urls.py:
```
from rest_framework_nested import routers

from .views import *

school_router = routers.DefaultRouter()
school_router.register(r'schools', SchoolViewSet, base_name='schools')

studentsets_router = routers.NestedDefaultRouter(school_router, r'schools', lookup='name')
studentsets_router.register(r'groups', GroupViewSet, base_name='groups')

urlpatterns = patterns(
    '',
    .....
    url(r'^school/(?P<slug>[-_\w]+)$', SchoolUIView.as_view(), name='school_ui_view'),
    url(r'^school-api/', include(school_router.urls)),
    url(r'^school-api/', include(studentsets_router.urls)),

)
```

I then try to add `('^edu-data/', '^school-api/')` into uncovered_includes exactly as it tells me to, and it complains they're still uncovered. Whether the culprit is the magic of Django REST Framework, or the [drf-nested-routers](https://github.com/alanjds/drf-nested-routers), I'm not sure, but one of them is definitely responsible.

**Comment by colons** [comment] 2017-02-08 11:41
Oh. I think the problem might be that you have two includes with the same regex, which instant coverage doesn't really know how to get to. This is a legitimate limitation that I hadn't thought about, but I am now, and hopefully will have some kind of good answer for in future. As a hacky workaround, for now, if you change one of those regexes to another, equivalent one (for instance `r'^scho{2}l-api/'` or `r'^[s]chool-api/'` or something), you should be able to address them individually in your `uncovered_includes`.

**Comment by Mihara** [comment] 2017-02-08 12:33
Yes, this solution worked, and is at least better than mine, which was linking up those routers at the root level. Thank you. :+1: 

**P.S.** You might want to document that limitation and the workaround for the 1.0 release, I think.

**Comment by colons** [comment] 2017-02-08 12:35
Cool! Glad it's working for you for the moment, and thanks for taking the time to file this issue! I'd like to actually make it work how you were expecting it to rather than adding documented complexity, I'll have a look at this when I get a moment.

**Comment by colons** [comment] 2017-02-08 13:12
@Mihara Am I right in assuming it was `test_all_urls_accounted_for` that was failing for you? Does the test case added in the commit above look like your configuration?

**Comment by colons** [comment] 2017-02-08 13:16
Looking at https://github.com/colons/instant-coverage/blob/master/instant_coverage/__init__.py#L46, it looks like the treatment of `uncovered_includes` is a comparison rather than a lookup, so I'm suddenly way less confident about the cause of this issue.

**Comment by Mihara** [comment] 2017-02-08 14:44
I was not getting an actual failure, I was getting an AssertionError telling me I had untested URLs I did not exclude, even though I had them listed in uncovered_includes with exactly the tuple it reported as uncovered.

What's even more bizarre is that I can't reproduce the error myself anymore, so it could have just been a serious derp on my part. O_o

**Comment by colons** [comment] 2017-02-08 14:46
Hah, fair enough. Well, I'll close this for now, and if you run into it again or work anything else out, feel free to reopen it. Thanks again for helping out :3

**Closed by colons** 2017-02-08 14:46 UTC
